### ISSUE TITLE
Graficke prvky na volebnim rozcestniku

### ISSUE THREAD

**Issue by b0rmann** [xaralis/pardubicky.pirati.cz#3]
Nejak ozivit. aspon znak mesta?

**Comment by b0rmann** [comment]
a asi pridat nejake ikonky web/program/kandidatka

**Comment by xaralis** [comment]
Jo, dal bych tam znak města a pár ikonek. Akorát ikony pro "program" a "kandidátku" fakt nevím jaký aby tam nebyly jen pro grafiku, ale aby fakt něco na první pohled vyjadřovaly. To už by mi přišlo lepší to tam pak nedávat.

**Comment by b0rmann** [comment]
k programu nejakou knizku. pro kandidat ikonku skupiny as... k webu - standartni ikonka webu :)
