### ISSUE TITLE
pár připomínek

### ISSUE THREAD

**Issue by Frettek23** [xaralis/pardubicky.pirati.cz#8]
volby 2018 - svitavy mají ke komunálním volbám jiný web - www.piratisvitavy.cz
U Rudoltic prosím změnit pořadí kandidátů na konci kandidátky takto: 10. Petr Beránek, 11. Jakub Loskot, 12. Lucie Sochorová, 13. Martin Václavík, 14. Zdeněk Stránský,
15. Soňa Zadražilová + ve spodní části programu jsou odrážky, které jsou ale bez odřádkování za sebou (chyba už ze starého template).
Přibude ještě Chrast a Polička - tím se to hezky zarovná :) Na textech makám
V mailu, kde jsem si na stav webů naposledy stěžoval najdeš aktuální fotku krajského sídla
Vyměnil bych pozice "kontaktní osoby" a "další kontakty" - aby byli kontaktní osoby nahoře
V sekci lidé by se mi líbilo, kdyby byl seznam všech členů. Často je skoro nemožné ho najít (je na wiki, ale to většina lidí neví)
K aktualitám nemám co dodat
Určitě bych tam chtěl link na nalodění - ať už v kontaktech (to bych preferoval), nebo na zvláštní stránce

**Comment by xaralis** [comment]
Rozděleno do jednotlivých samostatných úkolů.
