### ISSUE TITLE
doplnit Chrast a Poličku

### ISSUE THREAD

**Issue by Frettek23** [xaralis/pardubicky.pirati.cz#9]
v rozcestníku chybí Polička a Chrast - celé se to tím hezky uzavře. Na textech makám, ale mám také teď jiné priority. příští týden něco dodám

**Comment by xaralis** [comment]
Tím pádem to na launch nebude.

**Comment by Frettek23** [comment]
:D se mnou musíš česky.. co je to launch?

**Comment by xaralis** [comment]
Spuštění :)

**Comment by Frettek23** [comment]
jj dej to tam zatím prázdné, jako máš ty ostatní, že to bude doplněno. Já se na to zaměřím - zkusím to někomu možná zadat :)
